http:
  routers:
    static-route:
      entryPoints:
      - websecure
      rule: Host("<ADD_YOUR_DOMAIN>")
      service: static

  services:
    static:
      loadBalancer:
        servers:
        - url: "<ADD_LOCAL_IP_AND_PORT>"

  middlewares:
    secureHeaders:
      headers:
        sslRedirect: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

    user-auth:
      basicAuth:
        users:
          - "<ADD_YOUR_HTPASSWD>"   # Password for traefik http auth but you can also start traefik without a password

tls:
  options:
    default:
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      minVersion: VersionTLS12