api:
  dashboard: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
  
  websecure:
    address: :443
    http:
      middleware:
        - secureHeaders@file
      tls:
        certResolver: letsencrypt
        domains:
        - main: '<ADD_YOUR_DOMAIN'    # iltpwc.com
          sans:
            - '*.<ADD_YOUR_DOMAIN>'   # *.iltpwc.com

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: dynamic.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: <ADD_YOUR_MAIL>
      storage: acme.json
      dnsChallenge:
        provider: "digitalocean"  # change to your provider
        delayBeforeCheck: 120